### ISSUE TITLE
Vadim's TODO

### ISSUE THREAD

**Issue by vmarkovtsev** [FragileTech/ml-ops-quickstart#3]
These are the points that I want to help with:
- [x] Write the `README.md` (it currently references hvml).
- [x] Optimize YAML dependencies https://github.com/Guillemdb/ml-repo-template/pull/4
- [x] Switch the generation to Jinja2 templates. https://github.com/Guillemdb/ml-repo-template/commit/40f358273d4817a17ad2d7efbaf237204a372147
- [x] Presets (e.g., generic PyTorch, generic Tensorflow, etc.).
- [ ] Output the list of files that you will probably like to edit right after running the tool (e.g., `README.md`).
- [x] Switch from Travis to GitHub Action, both in the repo and in the template.
- [x] Ability to run on an existing repo and add only the missing files in an interactive mode.
- [ ] Analyze a repo for best practices and report common problems (e.g., packages in `requirements.txt` without pinned versions or no CI). That will be opinionated, and that's good because that's our tool.

**Comment by vmarkovtsev** [comment]
\+ we need to pick up a good name :smile:

**Comment by Guillemdb** [comment]
What about `pyboilerplate`? (Btw, I suck at choosing good names)

**Comment by vmarkovtsev** [comment]
LOL: https://pypi.org/project/pyboilerplate/

**Comment by vmarkovtsev** [comment]
https://pypi.org/project/python-boilerplate/ exists, too 😂

**Comment by Guillemdb** [comment]
Deprecated in favour of https://github.com/FragileTech/ml-ops-quickstart/issues/33
